apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: my-ingress-rules
 annotations:
  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
 ingressClassName: nginx
 rules:
 - host: website.192.168.1.4.nip.io
   http:
    paths:
    - path: /
      pathType: Prefix
      backend:
       service:
        name: my-website-service
        port:
         number: 8080